## config file to create cluster after kubctl and kind cluster installation 
## we create cluster by config.yml file 

kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

nodes: 
- role: control-plane
  image: kindest/node:v1.31.2
- role: worker
  image: kindest/node:v1.31.2
- role: worker
  image: kindest/node:v1.31.2
- role: worker
  image: kindest/node:v1.31.2


## To run this file for creating cluster by KIND Cluster that create 4 node: 1 is master-node, 3 worker-node & and it automatically join worker node by CNI (Container network interface)
  ```bash
  kind create cluster --name=cluster_name_here --config=config.yml
  ```
